name: Update JSON with Web Scraping

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main 
      
jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run main
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update JSON data [skip ci]" || echo "No changes to commit"
          git push
